# Generated by Django 3.1.14 on 2022-01-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('comments_num', models.PositiveIntegerField()),
                ('post_date_utc', models.DateField()),
                ('post_type', models.CharField(choices=[('PO', 'Post'), ('PA', 'Page'), ('DR', 'Draft')], default='DR', max_length=2)),
                ('protected', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=32)),
                ('is_top', models.BooleanField(default=False)),
            ],
        ),
    ]
