# Generated by Django 3.1.14 on 2022-01-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220108_0555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_date_utc',
        ),
        migrations.AddField(
            model_name='post',
            name='allow_comment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_date',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
