# Generated by Django 3.1.14 on 2022-01-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_post_comments_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
