# Generated by Django 3.1.14 on 2022-01-10 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_comments_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
