# Generated by Django 3.1.14 on 2022-01-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_post_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('is_admin', models.BooleanField(default=False)),
                ('url', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('parent', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(max_length=16),
        ),
    ]
