# Generated by Django 3.1.14 on 2022-01-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20220111_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
    ]
