# Generated by Django 3.1.14 on 2022-01-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_comment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='pid',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
