# Generated by Django 3.1.14 on 2022-01-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_comment_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
