# Generated by Django 3.1.14 on 2022-01-18 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='md5',
        ),
        migrations.AddField(
            model_name='media',
            name='path',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='media',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
